### ISSUE TITLE
Plugin Outline

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-filelisting#1]
A plugin is to be developed, which lists all the media files present in the current namespace (of the currently viewed page).

* [x] This automatic list can be integrated into a page via syntax or directly into the template and thus be automatically available at any time.
* [x] The list display can be expanded and collapsed. The current status is stored (local storage) per page in the browser. The default state can be defined in the configuration.
* [x] The list of files is displayed in a table with the following information
  * filename/namespace
  * file size
  * last change date
* [x] The current namespace is clearly marked. Subnamespaces are displayed and can be expanded by clicking on them.
* [x] The height of the list is fixed. If there are more files than there is space in the list, the list will be scrollable.
* [x] The table can be sorted by columns and filtered dynamically. Filters allow globbing syntax for filenames.
* [x] Files are linked directly and open in a new browser window (target="_blank")

![2017-10-11 14 26 56](https://user-images.githubusercontent.com/86426/31440517-8938a6d8-ae90-11e7-99d3-827a6a735b30.jpg)

Note: If the [Drag'n'Drop plugin](https://www.dokuwiki.org/plugin:dropfiles) is installed, files can also be dragged directly to the file list to trigger an upload without having to edit the current page. If files are dragged to a subnamespace, they are uploaded there instead of being uploaded to the current namespace. (This will be implemented in the Drag'n'Drop plugin and is not part of this ticket).

Estimation: 3 days

**Comment by micgro42** [comment]
cc @solewniczak

**Comment by solewniczak** [comment]
Sounds reasonable. 24 hours should be enough time. Subnamespaces should be expanded using ajax call or it will be enough to load everything during page load?

**Comment by splitbrain** [comment]
Yes, Ajax requests for the sub namespaces.

**Comment by solewniczak** [comment]
Ok, does the plugin need to work without JavaScript too?

**Comment by splitbrain** [comment]
basic stuff like showing the current namespace files should work, but all additional stuff like filtering, sorting or subnamespaces are fine to require JS

**Comment by solewniczak** [comment]
I've implemented basic html view. Check commit message for some design decisions I've made.

**Comment by splitbrain** [comment]
Looks good so far :+1:

**Comment by solewniczak** [comment]
Should the filtering work only for the current namespace or for all sub namespaces too? For all sub namespaces the ajax call becomes useless since we need to load all media files in advance. 

The solution which I believe is the most elegant is filtering only on expanded namespaces. I'll implement it this way but if you want it to work differently let me know.

**Comment by splitbrain** [comment]
yes, filtering should only apply to the currently open namespaces

**Comment by solewniczak** [comment]
Ok, I've just finished the plugin. Waiting for feedback.

**Comment by micgro42** [comment]
I like it! :+1:

There are some minor issues and a follow-up requirement. I will open tickets for each of those.
