### ISSUE TITLE
Removing files doesn't work

### ISSUE THREAD

**Issue by marcelomgarcia** [cosmocode/dokuwiki-plugin-filelisting#12]
Hi 

I'm using your plugins in my DokuWiki and I having troubles with the triad: filelisting, dropfiles and fetchmedia plugins. I created a name space in my Wiki to collect the documents, but I have problem with the "refresh" of the name space. 

First, when I dropped a file, I could see the file in the file listing window, but if I left the page, once I came back, there was nothing listed. I edited my page to include explicit the name space: 

meet_minutes:{{filelisting}}

Now it's working. That is, the upload and display works as expected. 

The next issue was when I tried to remove a file. The file is still show, and when I try to remove again, there is a red message saying to check persmissions:
""project_meeting_minutes_2017-12-13.docx" couldn't be deleted - check permissions."

The server is CentOS 7 with PHP 7 from Remi repository: http://rpms.famillecollet.com/. The CentOS 7 doesn't provide a newer version of PHP to use with the latest DokuWiki: php.x86_64  7.1.12-4.el7.remi. The Apache is from CentOS, 2.4.6-67.el7.centos.6.

Can you help with this issue? I think the problem is with the file list part. Is this right?

Best Regads

marcelo

**Comment by marcelomgarcia** [comment]
It seems that I put the tag "{{filelisting}}" on my "root" page, then everything works. So it seems the issue is with file listing/deleting/refreshing when working directly in a name space.

**Comment by solewniczak** [comment]
This should be fixed now, I believe.
