### ISSUE TITLE
Filter produces "are you sure you want to delete popup

### ISSUE THREAD

**Issue by alimat-nz** [cosmocode/dokuwiki-plugin-filelisting#16]
I was trying the filter option and instead of filtering it responds with a prompt asking if I am sure I want to delete the files instead. Is the filter box intended as a filter of the displayed list or is it actually a mass delete function?

**Comment by hb9tst** [comment]
The issue appears when pressing ENTER in the filter field, as this seems to push the "delete" button even if it hidden. It's a quite confusing issue for people who don't see what happens behind the scenes..
