### ISSUE TITLE
improve styling for the folder and file icons

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-filelisting#3]
The styling of the folder icon could be improved:

- [ ] some space between icon and title
- [ ] better vertical alignment (I think `vertical-align: middle;` on the SVG should do the trick)
- [ ] the absolute black of the folder icons is too harsh, maybe use `@ini_text` or the standard color from mdi?

![folder](https://user-images.githubusercontent.com/7372507/32271349-c1056fd2-bef9-11e7-9678-1204f6efcbdd.png)

**Comment by solewniczak** [comment]
What template do you use?

**Comment by micgro42** [comment]
The client uses a customized icke template.

**Comment by solewniczak** [comment]
Ok, I'll check it out.

**Comment by micgro42** [comment]
Feel free to do so if you want, however it is sufficient to test this plugin with the default DokuWiki template. The integration into the customer's template has its own budget.

The icke template itself is something I would consider rather "legacy".
