### ISSUE TITLE
Add delete functionality

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-filelisting#5]
The plugin integrates a file delete function. For this purpose, each file receives a checkbox to select the file. Selected files can then be deleted at the touch of a button after a confirmation prompt.

The DokuWiki option [`refcheck`](https://www.dokuwiki.org/config:refcheck) is respected. If it is turned on, files that are still in use cannot be deleted. The user will be informed.

File deletions are logged in the change history.

Estimation: 6 hours

**Comment by solewniczak** [comment]
Ok, I'll take it.

**Comment by solewniczak** [comment]
Ok, I've implemented basic html support for [media deletion](https://github.com/cosmocode/dokuwiki-plugin-filelisting/tree/addDeleteFunctionality). Do we need ajax support?

**Comment by micgro42** [comment]
No, we do not need ajax support (for now).
However, if javascript is available, then we do need an "Are you sure?"-kind of popup before actually deleting the files.

I tested the current branch and it seems to work fine so far :+1:

**Comment by ajshea** [comment]
This is nice, but most of the places I would use this plugin this is unwanted behavior. Can this be disabled with a per-instance flag?
